In [3]:
import pandas as pd
from datetime import datetime
from datetime import timedelta

In [4]:
# Load CSV
df = pd.read_csv("alfaskolen-b2.csv")

# Lesson ID
df["id"] = df.apply(lambda x: str(x.domenenummer)+"."+str(x.temanummer)+"."+str(x.leksonnummer), axis=1)

def getSchedule(year, month, day, goal, weekends=0):
    # Determine Schedule
    startDate = datetime(year, month, day)
    perDay = goal
    day =0
    schedule = []

    for i in range(len(df)):
        if i%perDay == perDay-1:
            day+=1
        date = startDate + timedelta(days=day)
        
        if weekends==0: # exclude weekends
            if date.weekday() >= 5:
                day+=2
            date = startDate + timedelta(days=day)

        #print(day, date)
        schedule.append(date)
    
    df["schedule"] = schedule

In [8]:
getSchedule(2020,3,6,5,1)
df.head(10)

,domene,domenenummer,tema,temanummer,leksonnummer,id,schedule
0,personlig,1,Familierelasjoner,1,1,1.1.1,2020-03-06
1,personlig,1,Familierelasjoner,1,2,1.1.2,2020-03-06
2,personlig,1,Familierelasjoner,1,3,1.1.3,2020-03-06
3,personlig,1,Familierelasjoner,1,4,1.1.4,2020-03-06
4,personlig,1,Familierelasjoner,1,5,1.1.5,2020-03-07
5,personlig,1,Familierelasjoner,1,6,1.1.6,2020-03-07
6,personlig,1,Familierelasjoner,1,7,1.1.7,2020-03-07
7,personlig,1,Familierelasjoner,1,8,1.1.8,2020-03-07
8,personlig,1,Familierelasjoner,1,9,1.1.9,2020-03-07
9,personlig,1,Familierelasjoner,1,10,1.1.10,2020-03-08

In [114]:
# Return the df as an excel file
df.to_excel("alfaskolen-b2-schedule.xlsx")